language: node_js

node_js:
  - 12

sudo: true

addons:
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run lint
  - npm run test -- --browsers ChromeHeadless
